### ISSUE TITLE
-hostfile Flag Not Working

### ISSUE THREAD

**Issue by NoPurposeInLife** [projectdiscovery/dnsx#233] opened 2022-09-04 04:09 UTC
### dnsx version:
v1.1.0

### Current Behavior:
1. DNSX does not resolve the supplied dns

### Expected Behavior:
1. DNSX resolves the supplied dns based on the entry in the host file

### Steps To Reproduce:
1. Add an entry to the host file such as 127.0.0.1 localhost
2. Run: echo "localhost" | dnsx -silent -hf
3. localhost is not resolved

**Comment by ehsandeep** [comment] 2022-09-28 22:01
Duplicate of https://github.com/projectdiscovery/dnsx/issues/222 and fixed.

**Closed by ehsandeep** 2022-09-28 22:01 UTC
Labels: Type: Bug
